services:
  web:
    container_name: web

    # ビルドコンテキスト
    build: 
      context: ./web
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    depends_on:
      - api

  api:
    container_name: api

    # ビルドコンテキスト
    build: 
      context: ./api
    ports:
      - 8080:8080
    
    # 先にDBを起動してからAPIを起動する
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    
    # DBのデータをボリュームに保存
    volumes:
      - db-storage:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

# ボリュームの作成
volumes:
  db-storage:

# Dockerネットワークはdocker-composeが自動で作成するものを使用